openapi: '3.1.1'
info:
  title: Civitai Orchestration - batchOCRSafetyClassification Recipe
  description: OpenAPI specification for the batchOCRSafetyClassification built-in recipe endpoint.
  version: v2
paths:
  /v2/consumer/recipes/batchOCRSafetyClassification:
    post:
      tags:
        - Recipes
      operationId: InvokeBatchOCRSafetyClassificationStepTemplate
      parameters:
        - name: experimental
          in: query
          schema:
            type: boolean
        - name: allowMatureContent
          in: query
          schema:
            type: boolean
        - name: whatif
          in: query
          schema:
            type: boolean
        - name: ephemeral
          in: query
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchOCRSafetyClassificationInput'
          text/json:
            schema:
              $ref: '#/components/schemas/BatchOCRSafetyClassificationInput'
          application/*+json:
            schema:
              $ref: '#/components/schemas/BatchOCRSafetyClassificationInput'
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchOCRSafetyClassificationOutput'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    BatchOCRSafetyClassificationInput:
      required:
        - mediaUrls
      type: object
      properties:
        mediaUrls:
          type: array
          items:
            type: string
            format: uri
      additionalProperties: false
    BatchOCRSafetyClassificationOutput:
      required:
        - results
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/BatchOCRSafetyClassificationResult'
      additionalProperties: false
    BatchOCRSafetyClassificationResult:
      required:
        - classification
        - mediaUrl
      type: object
      properties:
        mediaUrl:
          type: string
          format: uri
        classification:
          type: string
        text:
          type:
            - 'null'
            - string
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
            - 'null'
            - string
        title:
          type:
            - 'null'
            - string
        status:
          type:
            - 'null'
            - integer
          format: int32
        detail:
          type:
            - 'null'
            - string
        instance:
          type:
            - 'null'
            - string
      additionalProperties: { }
  securitySchemes:
    ApiKey:
      type: http
      description: Copy valid authorization token into field
      scheme: bearer
      bearerFormat: JWT
security:
  - { }
tags:
  - name: Recipes